In [1]:
import numpy as np
mylist = input().split()
m = np.array(mylist, dtype=int)
x = np.ones((m[0],m[1]))
x[::m[2], :m[1]] = 0
x[:m[0], ::m[3]] = 0
print(x)

 1 2 3 4


[[0. 0.]]


In [2]:
import numpy as np
mylist = input().split()
m = np.array(mylist, dtype=int)
x = np.zeros((m[1], m[0]))
x[::m[1]] = np.arange(0, m[0])
print(x)


 3 1


[[0. 1. 2.]]


In [4]:
import numpy as np
n = int(input('n:'))
x = np.zeros((n, n))
x[::2, :n] = 1
print(x)


n: 5


[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [5]:
import numpy as np
mylist = input("n:").split()
x = np.array(mylist, dtype=int)
x = np.where(x != 0, -1, x)
print(x)


n: 1 2 3


[-1 -1 -1]


In [6]:
import numpy as np
mylist = input("n:").split()
x = np.array(mylist, dtype=int)
x = np.where(x == 0, -1, x)
print(x)


n: 1 2 3


[1 2 3]


In [7]:
import numpy as np
mylist = input("n:").split()
x = np.array(mylist, dtype=int)
count = np.count_nonzero(x == 0)
print("Нулів:{0}".format(count))
print("Не нулів:{0}".format(x.size - count))


n: 0 1 2 3 0


Нулів:2
Не нулів:3


In [8]:
import numpy as np
n = int(input('n:'))
x = np.arange(n, -1, -1)
print(x)


n: 10


[10  9  8  7  6  5  4  3  2  1  0]


In [9]:
import numpy as np
x = np.arange(1, 121)
x.resize((4, 5, 6))
i, j, k = np.where(x == 100)
print("В матриці 4х5х6 індексом 100 елементу є ({0},{1},{2})".format(i, j, k))


В матриці 4х5х6 індексом 100 елементу є ([3],[1],[3])


In [10]:
import numpy as np
n = int(input('n:'))
x = np.arange(0, n + 1)
# x=np.greater(x,n/2) & np.less(x,(3*n)/4)
x[(x>(n/2)) & (x<((3*n)/4))]=0
# x = np.where((x > (n / 2)) & (x < ((3 * n) / 4)), 0, x)
print(x)



n: 10


[ 0  1  2  3  4  5  0  0  8  9 10]


In [11]:
import numpy as np
n = int(input('n:'))
x = np.random.randint(0, 99, n)
elem = np.unique(x)
size = np.size(elem)
print(x)
print('Количество уникальніх елементов: {0}'.format(size))

n: 30


[57 18 22 93 93  0 16  3 30 47 64 40 29 14 85 19 35 50 40 25 38 15 89 73
 73 66 27  0 49 98]
Количество уникальніх елементов: 26


In [3]:
# второе задание
import numpy as np
myarray=np.array([[2,1,-5,1],[1,-3,0,-6],[0,2,-1,2],[1,4,-7,6]],dtype=float)
endarray=np.array([8,9,-5,0],dtype=float)
result=np.linalg.solve(myarray,endarray)
print(result)
A=np.linalg.det(myarray)
print(A)
a1=np.array(myarray,dtype=float)
a1[:,0]=endarray
A1=np.linalg.det(a1)
a2=np.array(myarray,dtype=float)
a2[:,1]=endarray
A2=np.linalg.det(a2)
a3=np.array(myarray,dtype=float)
a3[:,2]=endarray
A3=np.linalg.det(a3)
a4=np.array(myarray,dtype=float)
a4[:,3]=endarray
A4=np.linalg.det(a4)
myList=[A1/A,A2/A,A3/A,A4/A]
print(myList)


[ 3. -4. -1.  1.]
27.0
[2.9999999999999982, -4.000000000000001, -1.0000000000000004, 1.0000000000000004]


In [14]:
# 3 задание
import numpy as np
a=np.array([[5,3,-1],[2,-2,0],[3,-1,2]])
b=np.array([[1,4,16],[-3,-2,0],[5,7,2]])
A=np.linalg.det(a)
B=np.linalg.det(b)
print(A)
print(B)
result=2*(A-0.5*B)+A*B
print(result)
print(np.allclose(myList,result))


-36.0
-156.0
5700.0
False


In [15]:
# 4 задание
import numpy as np
A=np.array([[4,2,1],[3,-2,0],[0,-1,2]],dtype=float)
B=np.array([[2,0,2],[5,-7,-2],[1,0,-1]],dtype=float)
res=np.linalg.solve(A,B)
print(res)
Aminus=np.linalg.inv(A)##ну надо найти обратную матрицу
res2=np.dot(Aminus,B)##результат вроде как должен быть по формуле x=A^(-1)*B
print(res2)
print(np.allclose(res,res2))


[[ 1.         -1.12903226  0.        ]
 [-1.          1.80645161  1.        ]
 [ 0.          0.90322581  0.        ]]
[[ 1.00000000e+00 -1.12903226e+00  0.00000000e+00]
 [-1.00000000e+00  1.80645161e+00  1.00000000e+00]
 [-5.55111512e-17  9.03225806e-01 -5.55111512e-17]]
True


In [18]:
# второе задание
import numpy as np
myarray=np.array([[2,1,-5,1],[1,-3,0,-6],[0,2,-1,2],[1,4,-7,6]],dtype=float)
endarray=np.array([8,9,-5,0],dtype=float)
result=np.linalg.solve(myarray,endarray)
print(result)
A=np.linalg.det(myarray)
print(A)

a1=np.array(myarray,dtype=float)
for i in range(len(myarray)):
    a1[:,i]=endarray
    A1=np.linalg.det(a1)
    myList = A1/A
    print(myList)  

# a1[:,0]=endarray
# A1=np.linalg.det(a1)
# a2=np.array(myarray,dtype=float)
# a2[:,1]=endarray
# A2=np.linalg.det(a2)
# a3=np.array(myarray,dtype=float)
# a3[:,2]=endarray
# A3=np.linalg.det(a3)
# a4=np.array(myarray,dtype=float)
# a4[:,3]=endarray
# A4=np.linalg.det(a4)
# myList=[A1/A,A2/A,A3/A,A4/A]
# print(myList)


[ 3. -4. -1.  1.]
27.0
2.9999999999999982
0.0
0.0
0.0
